# Generated by Django 4.2.5 on 2024-04-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('Jednoduchá', 'Jednoduchá'), ('Střední', 'Střední'), ('Težká', 'Težká')], max_length=10),
        ),
    ]
